### ISSUE TITLE
`README.md` supplies insufficent information about closed-source component

### ISSUE THREAD

**Issue by daveloyall** [votingworks/vxsuite-complete-system#263]
Hello!

First off, great work, thank you, keep it up!

A "popular press" news article states that "On November 8, the Granite State [(New Hampsire)] will pilot a new kind of voting machine that will use open-source software – software that everyone can examine – to tally the votes."

However, I'm unable to examine all the software.

I'll quote [some lines from `README.md`](https://github.com/votingworks/vxsuite-complete-system/blob/90f668b3380e0c0a93fd18f90008d99e859e944c/README.md?plain=1#L69-L80):

    ### Precinct Scanner (VxScan)
    
    This requires some other packages to be installed that, unfortunately, are not
    public. If you have access, go to https://github.com/votingworks/plustekctl and
    follow the install instructions. Once you've done that, this command will run
    all software services needed for precinct scanner:
    
    ```
    SCAN_WORKSPACE=/tmp ./run.sh precinct-scanner
    ```
    
    You may replace `/tmp` with any persistent path you like.

Look, I'm a Free Software/Libre Software developer.  I get it.  That repo \*probably\* contains some proprietary drivers for the "Plustek 776U" scanner.  You \*probably\* are bound by some EULA or something that prohibits you from sharing that repo.  (Side note: does merely marking the repo "private" actually cover you there?)

Getting out from under that mess is a separate issue.  This issue I'm reporting is about the README.

Please spell out what the situation is.  Please describe what steps you've taken to ensure that the issue doesn't impact voting.  Do you have a narrow, strictly defined interface with the scanner?  Is there an IOMMU between the CPU and the scanner?  Etc.

If you want us software developers to look over this thing and give our stamp of approval, you'd better say a lot about any chunks of it that we can't see.

Again, thank you for doing this and I wish you great success.  Keep it up!

**Comment by umbernhard** [comment]
Hey there, thanks for the suggestion! We are currently in the middle of running an election, so we'll circle back later to respond more in-depth.

**Comment by arsalansufi** [comment]
Thanks for flagging! We've since moved to a different scanner with our own open-source driver, that can be viewed here: https://github.com/votingworks/vxsuite/tree/main/libs/pdi-scanner
