### ISSUE TITLE
VX Admin Not Detecting Card Reader

### ISSUE THREAD

**Issue by Hydroxide4937** [votingworks/vxsuite-complete-system#279]
VX-Admin appears to be having issues recognizing the smart card reader on Ubuntu. Even after the PCSCD daemon is started via the terminal, it continues to display "Card Reader Not Detected". Are there specifications for what types of card readers will work? I was under the impression that any COTS ISO 7816 card reader should work. The card reader is recognized in the terminal, so I was wondering if some dependency was missed, affecting compatibility with the reader.

**Comment by eventualbuddha** [comment]
The front end checks for a particular device (for now). You can see that here: https://github.com/votingworks/vxsuite/blob/main/libs/utils/src/Hardware/utils.ts

I think you want this: [OmniKey 3121](https://www.amazon.com/HID-OMNIKEY-R31210320-01-Smart-Reader/dp/B06XY2XLWF/ref=mp_s_a_1_3?crid=27UKEF5AYE7EE&keywords=omni+key+card+reader&qid=1676778004&sprefix=omni+card+%2Caps%2C181&sr=8-3) or [OmniKey 3021](https://www.amazon.com/HID-OMNIKEY-3021-Smart-Reader/dp/B003BKV44C/ref=mp_s_a_1_4?crid=27UKEF5AYE7EE&keywords=omni+key+card+reader&qid=1676778004&sprefix=omni+card+%2Caps%2C181&sr=8-4).

**Comment by Hydroxide4937** [comment]
Thank you for pointing that out! That seems to have worked. Is there a way to get around the system admin card requirement for now, or is that not possible?

**Comment by arsalansufi** [comment]
There isn't a way around that requirement on an actual production system. But in development, we now provide a dev dock that allows mocking cards! https://github.com/votingworks/vxsuite/blob/5e8e3f376a621076b41b42db2032aa07d7b2e9fe/.env#L4
