### ISSUE TITLE
Configure pulseaudio suspend-on-idle in vx-ui rather than xinitrc

### ISSUE THREAD

**Issue by amcmanus** [votingworks/vxsuite-complete-system#394]
It's possible for a USB disconnect/error during boot to prevent disabling pulseaudio's suspend-on-idle feature. Rather than configuring this via `pactl` in xinitrc, move the configuration to the `vx-ui` user's config. This will ensure it is configured regardless of potential USB issues during X startup. 

Add the below snippet to `~vx-ui/.config/pulse/default.pa`
```
.include /etc/pulse/default.pa
.nofail
unload-module module-suspend-on-idle
.fail
```

**Comment by arsalansufi** [comment]
Done! https://github.com/votingworks/vxsuite-complete-system/pull/406
